# Generated by Django 3.1 on 2021-04-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_employeeuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmployeeUser',
        ),
    ]
