# Generated by Django 4.1.3 on 2022-12-14 16:46

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_delete_employeeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dosage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('0.25', '0.25'), ('0.5', '0.5'), ('1.0', '1.0'), ('1.5', '1.5')], max_length=255)),
                ('shift', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening')], max_length=50)),
            ],
            options={
                'db_table': 't_dosage',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('medicine_name', models.CharField(max_length=255)),
                ('duration', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7')], max_length=255)),
                ('instruction', models.CharField(choices=[('Before meal', 'Before meal'), ('After meal', 'After meal')], max_length=255)),
                ('note', models.TextField()),
                ('dosage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescription', to='crud.dosage')),
            ],
            options={
                'db_table': 't_prescription',
            },
        ),
    ]
